permalink: /:year/:month/:day/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

markdown: kramdown
highlighter: rouge 

paginate: 8
paginate_path: "page:num"

# presonal config
title: Elta's Blog
description: Elta's Blog, powered by Jekyll...
author: Dongxue Zhang

seo: 
  keyword: elta era
  description: elta's blog
config:
  js_dir:
  img_dir:
  css_dir:
